// Copyright Keeper Security, Inc. 2026
// SPDX-License-Identifier: MPL-2.0

package pamuser

const (
	SchemaDescription         = "Creates and manages a Keeper PAM User record in the vault."
	SchemaMarkdownDescription = "Creates and manages a Keeper **PAM User** record (`pamUser`) in the vault.\n\nA PAM User record stores privileged credentials (login/password) that can be associated with PAM Machines for rotation, connections, and tunneling."

	IDDescription                           = "The unique identifier (UID) of the PAM User record."
	IDMarkdownDescription                   = "The unique identifier (UID) of the PAM User record."
	TitleDescription                        = "Title of the PAM User record."
	TitleMarkdownDescription                = "Title of the PAM User record."
	LoginDescription                        = "Login (username) for the PAM User."
	LoginMarkdownDescription                = "Login (username) for the PAM User."
	PasswordDescription                     = "Password for the PAM User."
	PasswordMarkdownDescription             = "Password for the PAM User."
	FolderDescription                       = "Folder path or UID where the record will be stored."
	FolderMarkdownDescription               = "Folder path or UID where the record will be stored."
	NotesDescription                        = "Optional notes for the PAM User record."
	NotesMarkdownDescription                = "Optional notes for the PAM User record."
	DistinguishedNameDescription            = "LDAP distinguished name of the PAM User (e.g. CN=svc_myapp,OU=Service Accounts,DC=corp,DC=local)."
	DistinguishedNameMarkdownDescription    = "LDAP distinguished name of the PAM User (e.g. `CN=svc_myapp,OU=Service Accounts,DC=corp,DC=local`)."
	PrivatePEMKeyDescription                = "Private PEM key associated with the PAM User."
	PrivatePEMKeyMarkdownDescription        = "Private PEM key associated with the PAM User."
	PublicKeyDescription                    = "Public key associated with the PAM User."
	PublicKeyMarkdownDescription            = "Public key associated with the PAM User."
	PrivateKeyPassphraseDescription         = "Passphrase for the private key associated with the PAM User."
	PrivateKeyPassphraseMarkdownDescription = "Passphrase for the private key associated with the PAM User."
	ConnectDatabaseDescription              = "Database name the PAM User connects to."
	ConnectDatabaseMarkdownDescription      = "Database name the PAM User connects to."
	ManagedDescription                      = "Whether this PAM User account is managed by Keeper."
	ManagedMarkdownDescription              = "Whether this PAM User account is managed by Keeper."

	RotationSettingsDescription         = "Rotation settings for the PAM User record."
	RotationSettingsMarkdownDescription = "Rotation settings for the PAM User record. Configures password rotation via `pam rotation edit`.\n\n**Schedule:** use `on_demand` **or** at most one of `schedule_config`, `schedule_cron`, and `schedule_json` (they are mutually exclusive; see attribute descriptions)."

	RotProfileDescription                = "Rotation profile type: general (resource-based), iam_user (IAM/Azure user), or scripts_only (run PAM scripts only)."
	RotProfileMarkdownDescription        = "Rotation profile type: `general` (resource-based), `iam_user` (IAM/Azure user), or `scripts_only` (run PAM scripts only)."
	RotConfigDescription                 = "PAM Configuration UID to use for rotation."
	RotConfigMarkdownDescription         = "PAM Configuration UID to use for rotation."
	RotIamAadConfigDescription           = "PAM Configuration UID for IAM or Azure AD users. Used instead of resource when rotation_profile is iam_user."
	RotIamAadConfigMarkdownDescription   = "PAM Configuration UID for IAM or Azure AD users. Used instead of `resource` when `rotation_profile` is `iam_user`."
	RotResourceDescription               = "UID of the PAM resource record (machine or database) this user rotates on. Required when rotation_profile is general."
	RotResourceMarkdownDescription       = "UID of the PAM resource record (machine or database) this user rotates on. Required when `rotation_profile` is `general`."
	RotAdminUserDescription              = "UID of the PAM User record to use as admin credential when rotating."
	RotAdminUserMarkdownDescription      = "UID of the PAM User record to use as admin credential when rotating."
	RotEnabledDescription                = "Whether rotation is enabled for this PAM User."
	RotEnabledMarkdownDescription        = "Whether rotation is enabled for this PAM User."
	RotScheduleCronDescription           = "Cron schedule for rotation. Use 5-field (minutes first) or 6-field Quartz-style (seconds first), e.g. \"56 17 * * *\" or \"0 0 3 1 * ?\". Invalid expressions are rejected at plan time."
	RotScheduleCronMarkdownDescription   = "Cron schedule for rotation. Commander expects **5-field** (minutes first, e.g. `56 17 * * *`) or **6-field Quartz** (seconds first, e.g. `0 0 3 1 * ?`). Presets such as `@daily` are accepted when the parser supports them. Invalid expressions fail at **plan** time so the vault record is not created first."
	RotScheduleJSONDescription           = "JSON schedule for rotation (e.g. {\"type\": \"WEEKLY\", \"weekday\": \"SATURDAY\", \"time\": \"22:00\", \"tz\": \"America/New_York\"})."
	RotScheduleJSONMarkdownDescription   = "JSON schedule for rotation."
	RotOnDemandDescription               = "If true, rotation is on-demand (manual) only."
	RotOnDemandMarkdownDescription       = "If `true`, rotation is on-demand (manual) only."
	RotScheduleConfigDescription         = "If true, uses the schedule from the PAM Configuration."
	RotScheduleConfigMarkdownDescription = "If `true`, uses the schedule from the PAM Configuration instead of a per-record schedule."
	RotComplexityDescription             = "Password complexity for rotation: five integers length,upper,lower,digits,symbols (length 1\u201399; each count 0\u201399 per Keeper UI)."
	RotComplexityMarkdownDescription     = "Password complexity for rotation: `length,upper,lower,digits,symbols` as **five integers**. Password **length** must be **1\u201399**; upper, lower, digits, and symbols minimums must each be **0\u201399** (Keeper UI limits). Invalid values fail at plan time."

	ErrSummaryCreateFailed       = "PAM User Record Create Failed"
	ErrSummaryReadFailed         = "PAM User Record Read Failed"
	ErrSummaryUpdateFailed       = "PAM User Record Update Failed"
	ErrSummaryRotationEditFailed = "PAM User Rotation Edit Failed"

	ErrDetailCreateFailed       = "Something went wrong when creating the PAM User record."
	ErrDetailReadFailed         = "Something went wrong when reading the PAM User record."
	ErrDetailUpdateFailed       = "Something went wrong when updating the PAM User record."
	ErrDetailRotationEditFailed = "Something went wrong when configuring rotation for the PAM User record."
	ErrDetailRotationInfoFailed = "Something went wrong when reading rotation info for the PAM User record."

	// Commander field dot-notation keys for pamUser record-add / record-update.
	FieldLogin                = "f.login"
	FieldPassword             = "f.password"
	FieldDistinguishedName    = "f.text.distinguishedName"
	FieldPrivatePEMKey        = "f.secret.privatePEMKey"
	FieldPublicKey            = "f.secret.publicKey"
	FieldPrivateKeyPassphrase = "f.secret.privateKeyPassphrase"
	FieldConnectDatabase      = "f.text.connectDatabase"
	FieldManaged              = "f.checkbox.managed"

	// Commander pam rotation edit command and flags.
	CmdPamRotationEdit  = "pam rotation edit"
	CmdPamRotationInfo  = "pam rotation info"
	FlagConfig          = "--config"
	FlagIamAadConfig    = "--iam-aad-config"
	FlagRotationProfile = "--rotation-profile"
	FlagResource        = "--resource"
	FlagAdminUser       = "--admin-user"
	FlagEnable          = "--enable"
	FlagDisable         = "--disable"
	FlagForce           = "--force"
	FlagOnDemand        = "--on-demand"
	FlagScheduleCron    = "--schedulecron"
	FlagScheduleJSON    = "--schedulejson"
	FlagScheduleConfig  = "--schedule-config"
	FlagComplexity      = "--complexity"
	FlagRecordShort     = "-r"
)
