// Copyright Keeper Security, Inc. 2026
// SPDX-License-Identifier: MPL-2.0

//go:build ignore

// Generates tfplugindocs templates with Registry subcategories from doc_subcategories.yaml.
// Run from repo root: go run ./docs/generate_doc_templates.go
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	cmdprovider "github.com/Keeper-Security/terraform-provider-commander/internal/provider"
	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"gopkg.in/yaml.v3"
)

const (
	providerPrefix    = "commander_"
	docTemplateBody   = docTemplatePrefix + "%s" + docTemplateSuffix
	docTemplatePrefix = `---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "{{.Name}} {{.Type}} - {{.RenderedProviderName}}"
subcategory: "`
	docTemplateSuffix = `"
description: |-
{{ .Description | plainmarkdown | trimspace | prefixlines "  " }}
---

# {{.Name}} ({{.Type}})

{{ .Description | trimspace }}

{{ if .HasExamples -}}
## Example Usage

{{- range .ExampleFiles }}

{{ tffile . }}
{{- end }}
{{- end }}

{{ .SchemaMarkdown | trimspace }}
{{- if or .HasImport .HasImportIDConfig .HasImportIdentityConfig }}

## Import

Import is supported using the following syntax:
{{- end }}
{{- if .HasImportIdentityConfig }}

In Terraform v1.12.0 and later, the [` + "`import`" + ` block](https://developer.hashicorp.com/terraform/language/import) can be used with the ` + "`identity`" + ` attribute, for example:

{{tffile .ImportIdentityConfigFile }}

{{ .IdentitySchemaMarkdown | trimspace }}
{{- end }}
{{- if .HasImportIDConfig }}

In Terraform v1.5.0 and later, the [` + "`import`" + ` block](https://developer.hashicorp.com/terraform/language/import) can be used with the ` + "`id`" + ` attribute, for example:

{{tffile .ImportIDConfigFile }}
{{- end }}
{{- if .HasImport }}

The [` + "`terraform import`" + ` command](https://developer.hashicorp.com/terraform/cli/commands/import) can be used, for example:

{{codefile "shell" .ImportFile }}
{{- end }}
`
)

type categoryConfig struct {
	Resources   []string `yaml:"resources"`
	DataSources []string `yaml:"data_sources"`
}

type docSubcategoriesConfig struct {
	Categories map[string]categoryConfig `yaml:"categories"`
}

type typeMapping struct {
	kind        string // resources or data-sources
	name        string
	subcategory string
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "find repo root: %v\n", err)
		os.Exit(1)
	}

	cfg, err := loadConfig(filepath.Join(repoRoot, "docs", "doc_subcategories.yaml"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "load doc subcategories config: %v\n", err)
		os.Exit(1)
	}

	mappings, categoryNames, err := cfg.flatten()
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse doc subcategories config: %v\n", err)
		os.Exit(1)
	}

	registeredResources, registeredDataSources, err := registeredProviderTypes(context.Background())
	if err != nil {
		fmt.Fprintf(os.Stderr, "read provider schema: %v\n", err)
		os.Exit(1)
	}

	if err := validateAgainstProvider(mappings, registeredResources, registeredDataSources); err != nil {
		fmt.Fprintf(os.Stderr, "doc subcategories validation failed:\n%v\n", err)
		os.Exit(1)
	}

	resourceMappings := filterMappings(mappings, "resources")
	dataSourceMappings := filterMappings(mappings, "data-sources")

	if err := writeTemplates(repoRoot, "resources", resourceMappings); err != nil {
		fmt.Fprintf(os.Stderr, "write resource templates: %v\n", err)
		os.Exit(1)
	}
	if err := writeTemplates(repoRoot, "data-sources", dataSourceMappings); err != nil {
		fmt.Fprintf(os.Stderr, "write data source templates: %v\n", err)
		os.Exit(1)
	}
	if err := writeSubcategoriesFile(repoRoot, categoryNames); err != nil {
		fmt.Fprintf(os.Stderr, "write subcategories file: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("generated doc templates from docs/doc_subcategories.yaml")
}

func loadConfig(path string) (*docSubcategoriesConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg docSubcategoriesConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	if len(cfg.Categories) == 0 {
		return nil, fmt.Errorf("categories must not be empty")
	}
	return &cfg, nil
}

func (c *docSubcategoriesConfig) flatten() ([]typeMapping, []string, error) {
	categoryNames := make([]string, 0, len(c.Categories))
	for name := range c.Categories {
		categoryNames = append(categoryNames, name)
	}
	sort.Strings(categoryNames)

	seen := map[string]string{}
	var mappings []typeMapping

	for _, category := range categoryNames {
		entry := c.Categories[category]
		if strings.TrimSpace(category) == "" {
			return nil, nil, fmt.Errorf("category name must not be empty")
		}

		for _, name := range entry.Resources {
			name = strings.TrimSpace(name)
			if name == "" {
				return nil, nil, fmt.Errorf("category %q contains an empty resource name", category)
			}
			key := "resources:" + name
			if prev, ok := seen[key]; ok {
				return nil, nil, fmt.Errorf("resource %q is listed in multiple categories (%q and %q)", name, prev, category)
			}
			seen[key] = category
			mappings = append(mappings, typeMapping{kind: "resources", name: name, subcategory: category})
		}

		for _, name := range entry.DataSources {
			name = strings.TrimSpace(name)
			if name == "" {
				return nil, nil, fmt.Errorf("category %q contains an empty data source name", category)
			}
			key := "data-sources:" + name
			if prev, ok := seen[key]; ok {
				return nil, nil, fmt.Errorf("data source %q is listed in multiple categories (%q and %q)", name, prev, category)
			}
			seen[key] = category
			mappings = append(mappings, typeMapping{kind: "data-sources", name: name, subcategory: category})
		}
	}

	return mappings, categoryNames, nil
}

func registeredProviderTypes(ctx context.Context) (resources, dataSources []string, err error) {
	serverFactory := providerserver.NewProtocol6WithError(cmdprovider.New("dev")())
	server, err := serverFactory()
	if err != nil {
		return nil, nil, fmt.Errorf("create provider server: %w", err)
	}

	schema, err := server.GetProviderSchema(ctx, &tfprotov6.GetProviderSchemaRequest{})
	if err != nil {
		return nil, nil, fmt.Errorf("get provider schema: %w", err)
	}

	for name := range schema.ResourceSchemas {
		resources = append(resources, trimProviderPrefix(name))
	}
	for name := range schema.DataSourceSchemas {
		dataSources = append(dataSources, trimProviderPrefix(name))
	}

	sort.Strings(resources)
	sort.Strings(dataSources)
	return resources, dataSources, nil
}

func trimProviderPrefix(typeName string) string {
	return strings.TrimPrefix(typeName, providerPrefix)
}

func validateAgainstProvider(mappings []typeMapping, registeredResources, registeredDataSources []string) error {
	configuredResources := map[string]string{}
	configuredDataSources := map[string]string{}
	for _, m := range mappings {
		switch m.kind {
		case "resources":
			configuredResources[m.name] = m.subcategory
		case "data-sources":
			configuredDataSources[m.name] = m.subcategory
		}
	}

	var missingResources, missingDataSources, staleResources, staleDataSources []string

	for _, name := range registeredResources {
		if _, ok := configuredResources[name]; !ok {
			missingResources = append(missingResources, name)
		}
	}
	for _, name := range registeredDataSources {
		if _, ok := configuredDataSources[name]; !ok {
			missingDataSources = append(missingDataSources, name)
		}
	}

	registeredResourceSet := toSet(registeredResources)
	registeredDataSourceSet := toSet(registeredDataSources)
	for name := range configuredResources {
		if _, ok := registeredResourceSet[name]; !ok {
			staleResources = append(staleResources, name)
		}
	}
	for name := range configuredDataSources {
		if _, ok := registeredDataSourceSet[name]; !ok {
			staleDataSources = append(staleDataSources, name)
		}
	}

	sort.Strings(missingResources)
	sort.Strings(missingDataSources)
	sort.Strings(staleResources)
	sort.Strings(staleDataSources)

	var b strings.Builder
	if len(missingResources) > 0 {
		fmt.Fprintf(&b, "  missing resources in docs/doc_subcategories.yaml: %s\n", strings.Join(missingResources, ", "))
	}
	if len(missingDataSources) > 0 {
		fmt.Fprintf(&b, "  missing data sources in docs/doc_subcategories.yaml: %s\n", strings.Join(missingDataSources, ", "))
	}
	if len(staleResources) > 0 {
		fmt.Fprintf(&b, "  stale resources in docs/doc_subcategories.yaml (not registered in provider): %s\n", strings.Join(staleResources, ", "))
	}
	if len(staleDataSources) > 0 {
		fmt.Fprintf(&b, "  stale data sources in docs/doc_subcategories.yaml (not registered in provider): %s\n", strings.Join(staleDataSources, ", "))
	}
	if b.Len() == 0 {
		return nil
	}
	return fmt.Errorf("%s\nAdd or remove entries in docs/doc_subcategories.yaml, then re-run make generate", strings.TrimRight(b.String(), "\n"))
}

func toSet(values []string) map[string]struct{} {
	set := make(map[string]struct{}, len(values))
	for _, v := range values {
		set[v] = struct{}{}
	}
	return set
}

func filterMappings(mappings []typeMapping, kind string) []typeMapping {
	var out []typeMapping
	for _, m := range mappings {
		if m.kind == kind {
			out = append(out, m)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			if _, err := os.Stat(filepath.Join(dir, "internal", "provider")); err == nil {
				return dir, nil
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("provider repo root not found")
		}
		dir = parent
	}
}

func writeTemplates(repoRoot, kind string, mappings []typeMapping) error {
	dir := filepath.Join(repoRoot, "templates", kind)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	expected := map[string]struct{}{}
	for _, m := range mappings {
		expected[m.name+".md.tmpl"] = struct{}{}
		content := fmt.Sprintf(docTemplateBody, m.subcategory)
		path := filepath.Join(dir, m.name+".md.tmpl")
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md.tmpl") {
			continue
		}
		if _, ok := expected[entry.Name()]; !ok {
			if err := os.Remove(filepath.Join(dir, entry.Name())); err != nil {
				return err
			}
		}
	}
	return nil
}

func writeSubcategoriesFile(repoRoot string, categoryNames []string) error {
	path := filepath.Join(repoRoot, "docs", "subcategories.txt")
	return os.WriteFile(path, []byte(strings.Join(categoryNames, "\n")+"\n"), 0o644)
}
